services:
  db:
    image: postgres:15
    container_name: log_db
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: log_backend
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: logdb
      DB_USER: postgres
      DB_PASSWORD: postgres

  frontend:
    build: ./logs_frontend
    container_name: log_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./logs_frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./logs_frontend/.env

volumes:
  pgdata:
